Add GCM run to CI

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,9 +1,9 @@
 version: 2.1
 
 executors:
-  gcc-build-env:
+  gfortran:
     docker:
-      - image: gmao/ubuntu20-geos-env-mkl:v6.2.4-openmpi_4.0.5-gcc_10.3.0
+      - image: gmao/ubuntu20-geos-env-bcs:v6.2.4-openmpi_4.0.5-gcc_10.3.0-bcs_v10.19.2
         auth:
           username: $DOCKERHUB_USER
           password: $DOCKERHUB_AUTH_TOKEN
@@ -14,37 +14,52 @@ executors:
     resource_class: large
     #MEDIUM# resource_class: medium
 
+  ifort:
+    docker:
+      - image: gmao/ubuntu20-geos-env-bcs:v6.2.4-intelmpi_2021.2.0-intel_2021.2.0-bcs_v10.19.2
+        auth:
+          username: $DOCKERHUB_USER
+          password: $DOCKERHUB_AUTH_TOKEN
+    resource_class: large
+    #MEDIUM# resource_class: medium
+
 workflows:
-  version: 2.1
   build-test:
     jobs:
       - build-GEOSgcm:
-          context:
+          name: build-GEOSgcm-on-<< matrix.compiler >>
+          matrix:
+            parameters:
+              compiler: [gfortran, ifort]
+          context: 
             - docker-hub-creds
 
 jobs:
   build-GEOSgcm:
-    executor: gcc-build-env
+    parameters:
+      compiler:
+        type: string
+    executor: << parameters.compiler >>
     working_directory: /root/project
     steps:
       - checkout:
           path: GEOSgcm
       - run:
           name: "Versions etc"
-          command: mpirun --version && gfortran --version && echo $BASEDIR && pwd && ls
+          command: mpirun --version && << parameters.compiler>> --version && echo $BASEDIR && pwd && ls
       - run:
           name: "Mepo clone external repos"
           command: |
             cd ${CIRCLE_WORKING_DIRECTORY}/GEOSgcm
             mepo clone
-            mepo develop GEOSgcm_App GEOSgcm_GridComp
+            mepo develop GEOSgcm_App GEOSgcm_GridComp GMAO_Shared
             mepo status
       - run:
           name: "Mepo checkout-if-exists"
           command: |
             cd ${CIRCLE_WORKING_DIRECTORY}/GEOSgcm
             echo "${CIRCLE_BRANCH}"
-            if [ "${CIRCLE_BRANCH}" != "develop" ] && [ "${CIRCLE_BRANCH}" != "master" ] && [ "${CIRCLE_BRANCH}" != "main" ]
+            if [ "${CIRCLE_BRANCH}" != "develop" ] && [ "${CIRCLE_BRANCH}" != "main" ]
             then
                mepo checkout-if-exists ${CIRCLE_BRANCH}
             fi
@@ -53,12 +68,63 @@ jobs:
           name: "CMake"
           command: |
             cd ${CIRCLE_WORKING_DIRECTORY}/GEOSgcm
-            mkdir build
-            cd build
-            cmake .. -DBASEDIR=$BASEDIR/Linux -DCMAKE_Fortran_COMPILER=gfortran -DCMAKE_BUILD_TYPE=Debug -DUSE_F2PY=OFF
+            mkdir -p  ${CIRCLE_WORKING_DIRECTORY}/workspace/build-GEOSgcm
+            cd ${CIRCLE_WORKING_DIRECTORY}/workspace/build-GEOSgcm
+            cmake ${CIRCLE_WORKING_DIRECTORY}/GEOSgcm -DBASEDIR=$BASEDIR/Linux -DCMAKE_Fortran_COMPILER=<< parameters.compiler >> -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=${CIRCLE_WORKING_DIRECTORY}/workspace/install-GEOSgcm -DUSE_F2PY=OFF 
       - run:
-          name: "Build"
+          name: "Build and install"
           command: |
-            cd ${CIRCLE_WORKING_DIRECTORY}/GEOSgcm/build
+            cd ${CIRCLE_WORKING_DIRECTORY}/workspace/build-GEOSgcm
             make -j"$(nproc)" install
             #MEDIUM# make -j4 install
+      # We need to persist the install for the next step
+      # but only if we are running gcm tests
+      - persist_to_workspace:
+          root: workspace
+          paths:
+            - install-GEOSgcm
+
+  make-gcm-exp:
+    parameters:
+      compiler:
+        type: string
+    executor: << parameters.compiler >>
+    working_directory: /root/project
+    steps:
+      - attach_workspace:
+          at: workspace
+      - run:
+          name: "Run gcm_setup"
+          command: |
+            cd ${CIRCLE_WORKING_DIRECTORY}/workspace/install-GEOSgcm/bin
+            /TinyBCs-GitV10/scripts/create_expt.py test-gcm-c12 --expdir ${CIRCLE_WORKING_DIRECTORY}/workspace
+      - run:
+          name: "Run makeoneday"
+          command: |
+            cd ${CIRCLE_WORKING_DIRECTORY}/workspace/test-gcm-c12
+            /TinyBCs-GitV10/scripts/makeoneday.bash 6hr nxy 1 6
+      - run:
+          name: "Run gcm_run.j"
+          command: |
+            cd ${CIRCLE_WORKING_DIRECTORY}/workspace/test-gcm-c12
+            ./gcm_run.j |& tee run.log
+      - run:
+          name: "Check for EGRESS"
+          command: |
+            cd ${CIRCLE_WORKING_DIRECTORY}/workspace/test-gcm-c12
+
+            SCRDIR=$(find . -type d -name 'scratch*')
+
+            if [[ -f $SCRDIR/EGRESS ]]
+            then
+               echo "EGRESS found!"
+            else
+               echo "EGRESS not found!"
+               exit 1
+            fi
+      - run:
+          name: "Cat log file"
+          command: |
+            cd ${CIRCLE_WORKING_DIRECTORY}/workspace/test-gcm-c12
+
+            cat *.log
